### ISSUE TITLE
[You Only Look Once] Class 20개 학습 np_label[grid_x_index][grid_y_index] index error 발생

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/You_Only_Look_Once#101]
학습시 다음과 같은 에러가 납니다.
전에는 이런 에러가 없었던 것 같은데
Augmentation시, 부동소수점의 label 값이 `int()`로 변환되면서 올림이 일어나서 index에러가 나는 것으로
추정됩니다.

한번 확인해보겠습니다.

```bash
epoch: [1/16000], total step: [30/17136000], batch step [30/1071], lr: 0.001, total_loss: 159.7527, coord1: 84.4344, size1: 71.2426, noobj_clss: 0.4048, objness1: 1.2692, class_loss: 2.4017
epoch: [1/16000], total step: [40/17136000], batch step [40/1071], lr: 0.001, total_loss: 148.3626, coord1: 72.7185, size1: 69.3889, noobj_clss: 1.3785, objness1: 1.2605, class_loss: 3.6164
epoch: [1/16000], total step: [50/17136000], batch step [50/1071], lr: 0.001, total_loss: 17.8654, coord1: 7.7819, size1: 6.8852, noobj_clss: 0.2537, objness1: 1.0417, class_loss: 1.9030
epoch: [1/16000], total step: [60/17136000], batch step [60/1071], lr: 0.001, total_loss: 28.2859, coord1: 15.4291, size1: 8.8064, noobj_clss: 0.2088, objness1: 1.8481, class_loss: 1.9934
epoch: [1/16000], total step: [70/17136000], batch step [70/1071], lr: 0.001, total_loss: 58.0039, coord1: 31.7879, size1: 21.8455, noobj_clss: 0.1341, objness1: 1.8722, class_loss: 2.3643
epoch: [1/16000], total step: [80/17136000], batch step [80/1071], lr: 0.001, total_loss: 13.2648, coord1: 6.6024, size1: 3.1327, noobj_clss: 0.4123, objness1: 1.4370, class_loss: 1.6804
epoch: [1/16000], total step: [90/17136000], batch step [90/1071], lr: 0.001, total_loss: 7.9065, coord1: 2.2914, size1: 3.2226, noobj_clss: 0.5510, objness1: 0.7447, class_loss: 1.0968
epoch: [1/16000], total step: [100/17136000], batch step [100/1071], lr: 0.001, total_loss: 10.9651, coord1: 4.1706, size1: 4.0657, noobj_clss: 0.2588, objness1: 1.2883, class_loss: 1.1818
epoch: [1/16000], total step: [200/17136000], batch step [200/1071], lr: 0.001, total_loss: 12.4949, coord1: 5.6460, size1: 3.4982, noobj_clss: 0.5134, objness1: 1.2569, class_loss: 1.5804
epoch: [1/16000], total step: [300/17136000], batch step [300/1071], lr: 0.001, total_loss: 7.5501, coord1: 2.9059, size1: 1.1933, noobj_clss: 0.3017, objness1: 1.2945, class_loss: 1.8548
epoch: [1/16000], total step: [400/17136000], batch step [400/1071], lr: 0.001, total_loss: 10.2634, coord1: 3.2991, size1: 3.8565, noobj_clss: 0.4008, objness1: 1.2543, class_loss: 1.4528
Traceback (most recent call last):
  File "main.py", line 63, in <module>
    main()
  File "main.py", line 57, in main
    train(params)
  File "/home/keti-1080ti/Documents/dev/yolov1/train.py", line 121, in train
    for i, (images, labels, sizes) in enumerate(train_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/keti-1080ti/Documents/dev/yolov1/utilities/dataloader.py", line 65, in detection_collate
    np_label[grid_x_index][grid_y_index] = np.array([objectness, x_offset, y_offset, w_ratio, h_ratio, classes])
IndexError: index 7 is out of bounds for axis 0 with size 7
```

**Comment by insurgent92** [comment]
https://github.com/DeepBaksuVision/You_Only_Look_Once/blob/5a55a033d8356a2e0969da5279d9caded89a1f5d/utilities/utils.py#L109
혹시 여기에서 발생하는 문제일수도 있지 않을까요..?

**Comment by insurgent92** [comment]
https://github.com/DeepBaksuVision/You_Only_Look_Once/blob/5a55a033d8356a2e0969da5279d9caded89a1f5d/utilities/utils.py#L109

제가 짠 코드에서 소숫점 3자리에서 반올림하는 코드가 들어있네요
간단하게 확인한 결과 이 문제가 확실합니다.
